In [7]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

import numpy as np
import pandas as pd

In [165]:
df = pd.read_csv("data/heart.csv")

In [166]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
0   52    1   0       125   212    0        1      168      0      1.0      2   2     3       0
1   53    1   0       140   203    1        0      155      1      3.1      0   0     3       0
2   70    1   0       145   174    0        1      125      1      2.6      0   0     3       0
3   61    1   0       148   203    0        1      161      0      0.0      2   1     3       0
4   62    0   0       138   294    1        1      106      0      1.9      1   3     2       0

In [167]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [168]:
X = df.drop("target", axis=1)
y = df["target"]

In [169]:
scaler = StandardScaler()

scaled_data = scaler.fit_transform(X)

In [170]:
scaled_data

array([[-0.26843658,  0.66150409, -0.91575542, ...,  0.99543334,
         1.20922066,  1.08985168],
       [-0.15815703,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       [ 1.71659547,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       ...,
       [-0.81983438,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459, -0.52212231],
       [-0.4889957 , -1.51170646, -0.91575542, ...,  0.99543334,
        -0.73197147, -0.52212231],
       [-0.04787747,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459,  1.08985168]])

In [171]:
X_train, X_test, y_train, y_test = train_test_split(scaled_data, y, test_size=0.2)

In [172]:
model = Sequential([
    Dense(64, activation="relu", input_shape=(13,)),
    Dense(32, activation="relu"),
    Dense(16, activation="relu"),
    Dense(1, activation="sigmoid")
])

In [173]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [174]:
model.fit(X_train, y_train, epochs=10);

Epoch 1/10
26/26 [==============================] - 1s 11ms/step - loss: 0.5844 - accuracy: 0.7793
Epoch 2/10
26/26 [==============================] - 0s 13ms/step - loss: 0.4394 - accuracy: 0.8341
Epoch 3/10
26/26 [==============================] - 0s 13ms/step - loss: 0.3596 - accuracy: 0.8573
Epoch 4/10
26/26 [==============================] - 0s 12ms/step - loss: 0.3191 - accuracy: 0.8793
Epoch 5/10
26/26 [==============================] - 0s 11ms/step - loss: 0.2907 - accuracy: 0.8854
Epoch 6/10
26/26 [==============================] - 0s 14ms/step - loss: 0.2693 - accuracy: 0.8902
Epoch 7/10
26/26 [==============================] - 0s 11ms/step - loss: 0.2492 - accuracy: 0.9024
Epoch 8/10
26/26 [==============================] - 0s 14ms/step - loss: 0.2309 - accuracy: 0.9037
Epoch 9/10
26/26 [==============================] - 0s 14ms/step - loss: 0.2117 - accuracy: 0.9159
Epoch 10/10
26/26 [==============================] - 0s 13ms/step - loss: 0.1940 - accuracy: 0.9207


In [175]:
loss, accuracy = model.evaluate(X_test, y_test)

7/7 [==============================] - 0s 9ms/step - loss: 0.2088 - accuracy: 0.9073


In [176]:
loss

0.20880086719989777

In [177]:
accuracy

0.9073171019554138

# Lets try a regression model

In [ ]:
from sklearn.datasets import fetch_california_housing

In [ ]:
cali = fetch_california_housing(as_frame=True)
df = pd.DataFrame(cali.data, columns=cali.feature_names)
df["target"] = pd.Series(cali.target)

In [93]:
df.isna().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
target        0
dtype: int64

In [94]:
df.dtypes

MedInc        float64
HouseAge      float64
AveRooms      float64
AveBedrms     float64
Population    float64
AveOccup      float64
Latitude      float64
Longitude     float64
target        float64
dtype: object

In [95]:
X = df.drop("target", axis=1)
y = df.target

In [97]:
X_scaled = scaler.fit_transform(X)

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2)

In [103]:
model = Sequential([
    Dense(64, activation="relu", input_shape=[X_train.shape[1]]),
    Dense(64, activation="relu"),
    Dense(1)
])

In [182]:
model.compile(optimizer="adam", loss="mae")

In [183]:
model.fit(X_train, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
21/21 [==============================] - 1s 19ms/step - loss: 0.1262 - val_loss: 0.0786
Epoch 2/100
21/21 [==============================] - 0s 12ms/step - loss: 0.1086 - val_loss: 0.0728
Epoch 3/100
21/21 [==============================] - 0s 14ms/step - loss: 0.0984 - val_loss: 0.0688
Epoch 4/100
21/21 [==============================] - 0s 13ms/step - loss: 0.0905 - val_loss: 0.0647
Epoch 5/100
21/21 [==============================] - 0s 15ms/step - loss: 0.0835 - val_loss: 0.0630
Epoch 6/100
21/21 [==============================] - 0s 13ms/step - loss: 0.0754 - val_loss: 0.0580
Epoch 7/100
21/21 [==============================] - 0s 14ms/step - loss: 0.0693 - val_loss: 0.0559
Epoch 8/100
21/21 [==============================] - 0s 16ms/step - loss: 0.0648 - val_loss: 0.0530
Epoch 9/100
21/21 [==============================] - 0s 17ms/step - loss: 0.0597 - val_loss: 0.0497
Epoch 10/100
21/21 [==============================] - 0s 14ms/step - loss: 0.0553 - val_loss: 0.0467

In [184]:
model.evaluate(X_test, y_test)

7/7 [==============================] - 0s 6ms/step - loss: 0.0147


0.014689899049699306

In [2]:
mnist = tf.keras.datasets.mnist

In [4]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 5s 0us/step


In [5]:
X_train, X_test = X_train / 255, X_test / 255.0

In [26]:
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation="relu"),
    Dropout(0.2),
    Dense(10),
])

In [27]:
predictions = model(X_train[:1]).numpy()
predictions

array([[ 0.5654353 ,  0.06812111, -0.69708675, -0.01568498,  0.5699701 ,
        -0.04040892, -0.3178453 ,  0.00785166,  0.19648081, -0.20636703]],
      dtype=float32)

In [28]:
tf.nn.softmax(predictions).numpy()

array([[0.16286159, 0.09904621, 0.04607998, 0.09108384, 0.1636018 ,
        0.0888595 , 0.06733095, 0.09325308, 0.11261176, 0.07527126]],
      dtype=float32)

In [29]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [30]:
loss_fn(y_train[:1], predictions).numpy()

2.4206986

In [31]:
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])

In [33]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 24s 12ms/step - loss: 0.2923 - accuracy: 0.9148
Epoch 2/10
1875/1875 [==============================] - 23s 12ms/step - loss: 0.1402 - accuracy: 0.9586
Epoch 3/10
1875/1875 [==============================] - 23s 12ms/step - loss: 0.1082 - accuracy: 0.9672
Epoch 4/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0858 - accuracy: 0.9735
Epoch 5/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0733 - accuracy: 0.9769
Epoch 6/10
1875/1875 [==============================] - 23s 12ms/step - loss: 0.0648 - accuracy: 0.9792
Epoch 7/10
1875/1875 [==============================] - 24s 13ms/step - loss: 0.0579 - accuracy: 0.9805
Epoch 8/10
1875/1875 [==============================] - 23s 12ms/step - loss: 0.0511 - accuracy: 0.9832
Epoch 9/10
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0489 - accuracy: 0.9845
Epoch 10/10
1875/1875 [==============================] - 22s 12m

In [36]:
model.evaluate(X_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0703 - accuracy: 0.9789 - 1s/epoch - 4ms/step


[0.07027527689933777, 0.9789000749588013]

In [41]:
predictions = Sequential([
    model, tf.keras.layers.Softmax()
])

In [42]:
prediction = predictions(X_train[:5])

In [45]:
prediction

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.7418916e-14, 3.1502252e-11, 7.5430622e-14, 1.9278312e-02,
        2.2004169e-26, 9.8072171e-01, 8.6424779e-15, 8.8423312e-13,
        2.3121465e-14, 1.1677584e-11],
       [9.9999964e-01, 5.5998345e-11, 4.1627010e-07, 1.4710679e-09,
        8.9442226e-17, 1.1528281e-09, 2.1874089e-09, 2.3599811e-09,
        3.5852265e-12, 1.5798988e-09],
       [2.1368203e-14, 9.6745680e-07, 1.3291342e-06, 6.5890593e-10,
        9.9999607e-01, 3.8207194e-08, 2.1012889e-11, 3.3537694e-07,
        1.8003109e-07, 1.0183006e-06],
       [4.9702984e-09, 9.9999881e-01, 1.5185840e-08, 1.9551048e-10,
        7.4396851e-08, 3.9580342e-10, 2.2960664e-09, 6.2934339e-07,
        4.3004258e-07, 5.8446645e-13],
       [1.0373136e-13, 3.0537774e-07, 2.7178577e-11, 3.0439798e-05,
        2.5325595e-05, 1.2245444e-09, 4.6136950e-14, 1.0561679e-05,
        4.4103672e-06, 9.9992895e-01]], dtype=float32)>