In [1]:
import numpy as np

# Datatypes and attributes

In [2]:
# Nunmpy's main datatype is a ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.0], [4, 5, 6.6]])

In [8]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.6]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)

In [18]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.6

# Creating Numpy arrays

In [2]:
import numpy as np
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [8]:
ones = np.ones((2, 3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
zeroes = np.zeros((2, 3), dtype=int)
zeroes

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

In [18]:
random_arr = np.random.randint(low=1, high=10, size=(2, 3), dtype=int)
random_arr

array([[1, 6, 7],
       [3, 4, 8]])

In [19]:
random_arr.shape

(2, 3)

In [21]:
random_arr_2 = np.random.random((2, 3))
random_arr_2

array([[0.22586593, 0.94955948, 0.15158681],
       [0.28114181, 0.48521306, 0.58025331]])

In [22]:
random_arr_3 = np.random.rand(5, 3)
random_arr_3

array([[0.66699803, 0.97809311, 0.10473065],
       [0.19558684, 0.76836832, 0.12607547],
       [0.84708004, 0.13940212, 0.8667032 ],
       [0.11731768, 0.73594145, 0.10469178],
       [0.28919953, 0.96526572, 0.96316882]])

In [23]:
# Psuedo-random numbers
np.random.seed()

In [28]:
np.random.seed(0)
random_arr_4 = np.random.randint(10, size=(5, 3))
random_arr_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [36]:
np.random.seed(7)
random_arr_5 = np.random.random((2, 3))
random_arr_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587]])