# Introduction to scikit-learn

This notebook demonstrates some of the most useful functions of the beautiful Scikit-Learn library.

What we're going to cover


0. An end-to-end Scikit-Learn workflow
1. Getting the data ready
2. Choose the right estimator/algorithm for our problem
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together!

## 0. An end-to-end Scikit-Learn workflow

In [3]:
# 1. Get the data ready
import pandas as pd
import numpy as np

heart_disease = pd.read_csv("heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [11]:
# Create X (feautres matrix)
X =  heart_disease.drop("target", axis=1)

# Create y (labels)
y = heart_disease["target"]

In [68]:
# 2. Choose the right model and hyperparameters
# This is a classification problem because we want to determine if X = heart disease

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 90)

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 90,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [69]:
# Fit the model to the data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [70]:
clf.fit(X_train, y_train);
X_train.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
112   64    0   2       140   313    0        1      133      0      0.2   
157   35    1   1       122   192    0        1      174      0      0.0   
24    40    1   3       140   199    0        1      178      1      1.4   
254   59    1   3       160   273    0        0      125      0      0.0   
223   56    0   0       200   288    1        0      133      1      4.0   

     slope  ca  thal  
112      2   0     3  
157      2   0     2  
24       2   0     3  
254      2   0     2  
223      0   2     3

In [24]:
# Make a prediction
y_label = clf.predict(np.array([0, 2, 3, 4]))

C:\Users\mahou\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [71]:
y_preds = clf.predict(X_test)

In [72]:
y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [73]:
y_test.head()

238    0
272    0
245    0
264    0
44     1
Name: target, dtype: int64

In [74]:
# 4. Evaluate the model on the training data and test data
clf.score(X_train, y_train)

1.0

In [75]:
clf.score(X_test, y_test)

0.7868852459016393

In [39]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.83      0.70      0.76        27
           1       0.79      0.88      0.83        34

    accuracy                           0.80        61
   macro avg       0.81      0.79      0.80        61
weighted avg       0.81      0.80      0.80        61



In [40]:
confusion_matrix(y_test, y_preds)

array([[19,  8],
       [ 4, 30]], dtype=int64)

In [41]:
accuracy_score(y_test, y_preds)

0.8032786885245902

In [78]:
# 5. Improve a model
# Try different amount of n_estimators

np.random.seed(10)
for i in range(10, 100, 10):
    print("Trying model with {} estimators".format(i))
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print("Model accuracy on test set: {} %".format(clf.score(X_test, y_test)))
    print()

Trying model with 10 estimators
Model accuracy on test set: 0.7868852459016393 %

Trying model with 20 estimators
Model accuracy on test set: 0.8032786885245902 %

Trying model with 30 estimators
Model accuracy on test set: 0.819672131147541 %

Trying model with 40 estimators
Model accuracy on test set: 0.7868852459016393 %

Trying model with 50 estimators
Model accuracy on test set: 0.819672131147541 %

Trying model with 60 estimators
Model accuracy on test set: 0.7868852459016393 %

Trying model with 70 estimators
Model accuracy on test set: 0.819672131147541 %

Trying model with 80 estimators
Model accuracy on test set: 0.819672131147541 %

Trying model with 90 estimators
Model accuracy on test set: 0.819672131147541 %



In [67]:
# 6. Save a model and load it
import pickle

pickle.dump(clf, open("random-forest-model1.pkl", "wb"))

In [79]:
loaded_model = pickle.load(open("Random-forest-model1.pkl", "rb"))
loaded_model.score(X_test, y_test)

0.9672131147540983

# Retry again

In [81]:
heart_data = pd.read_csv("heart-disease.csv")
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [95]:
X = heart_data.drop("target", axis=1)
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [96]:
y = heart_data["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [103]:
clf = RandomForestClassifier()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [104]:
clf.fit(X_train, y_train);

In [105]:
y_pred = clf.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [106]:
clf.score(X_train, y_train)

1.0

In [102]:
clf.score(X_test, y_test)

0.8524590163934426

# Retry again

In [113]:
heart_data = pd.read_csv("heart-disease.csv")
X = heart_data.drop("target", axis=1)
y = heart_data["target"]

clf = RandomForestClassifier(n_estimators=80)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

clf.score(X_test, y_test)

0.8032786885245902